# Jekyll config

exclude: [
  bower.json,
  CNAME,
  Gemfile,
  Gemfile.lock,
  Gruntfile.js,
  LICENSE,
  node_modules,
  package.json,
  README.md
]

safe: true

# switched from compressed to expanded due to sass map issue
sass:
  style: :expanded

