# Jekyll config

exclude: [
  bower.json,
  CNAME,
  Gemfile,
  Gemfile.lock,
  Gruntfile.js,
  LICENSE,
  node_modules,
  package.json,
  README.md
]

safe: true

# sass maps seem to have issues when minified using compressed option
sass:
  style: :compressed

