# Jekyll config

title: Joseph Abrahams - Washington, D.C.
description: Vice President of Engineering at Mariana Tek.

url: https://josephabrahams.com
baseurl: ""

plugins:
  - jekyll-sitemap

safe: true

sass:
  sass_dir: _sass
  style: :compressed

exclude:
  - bower.json
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - package.json
  - package-lock.json
  - README.md
